# TABLE_STATUS_COLUMNS = ['FREQUENTANDO', 'TRANCADO', 'EM_CURSO', 'INTEGRALIZADA', 'CONCLUÍDA', 'ABANDONO', 'DESLIGADO', 'TRANSF_INT', 'TRANSF_EXT', 'TOTAL DE ALUNOS']
TABLE_STATUS_COLUMNS = ['EM_CURSO', 'INTEGRALIZADA', 'CONCLUÍDA', 'ABANDONO', 'DESLIGADO', 'TRANSF_EXT', 'TOTAL DE ALUNOS']
TABLE_TRANC = ['MATRICULA_TRANC', 'NOME_TRANC', 'CURSO_TRANC', 'STATUS_TRANC']